### ISSUE TITLE
MasterDetailExample.Droid crashes with 'System.InvalidOperationException: NavigationPage must have a root Page before being used'

### ISSUE THREAD

**Issue by ehuna** [MvvmCross/MvvmCross#2303]
To help us fix your issue, please provide the information in the below template. 

> Note: There is often little we can do without a minimal reproducible sample of the issue, so please provide that in a **standalone git repository** and link it here.
>
> Please only file bugs verified on latest version of MvvmCross and _stable_ Xamarin tools

### Steps to reproduce

1. Clone MvvmCross

2. Open the MvvmCross_All.sln in ViS 2017

3. Compile TestProjects/Forms/MasterDetail/MasterDetailExample.Droid and all of its dependencies - it works, 15 projects.

4. Setup an Android Emulator and set the startup project as TestProjects/Forms/MasterDetail/MasterDetailExample.Droid as the startup project then run.

### Expected behavior
MasterDetailExample.Droid is deployed to the Android Emulator and runs without exceptions

### Actual behavior
MasterDetailExample.Droid is deployed to the Android Emulator but when it runs, it crashes with the following exception -

`10-27 23:01:44.470 I/MonoDroid( 3625): UNHANDLED EXCEPTION:
10-27 23:01:44.510 I/MonoDroid( 3625): System.InvalidOperationException: NavigationPage must have a root Page before being used. Either call PushAsync with a valid Page, or pass a Page to the constructor before usage.
10-27 23:01:44.510 I/MonoDroid( 3625):   at Xamarin.Forms.Platform.Android.Platform.UpdateActionBar () [0x00085] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:463 
10-27 23:01:44.510 I/MonoDroid( 3625):   at Xamarin.Forms.Platform.Android.Platform.SetPage (Xamarin.Forms.Page newRoot) [0x000a3] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Platform.cs:420 
10-27 23:01:44.510 I/MonoDroid( 3625):   at Xamarin.Forms.Platform.Android.FormsApplicationActivity.InternalSetPage (Xamarin.Forms.Page page) [0x000b7] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\FormsApplicationActivity.cs:290 
10-27 23:01:44.510 I/MonoDroid( 3625):   at Xamarin.Forms.Platform.Android.FormsApplicationActivity.SetMainPage () [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\FormsApplicationActivity.cs:309 
10-27 23:01:44.510 I/MonoDroid( 3625):   at Xamarin.Forms.Platform.Android.FormsApplicationActivity.LoadApplication (Xamarin.Forms.Application application) [0x00045] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\FormsApplicationActivity.cs:115 
10-27 23:01:44.510 I/MonoDroid( 3625):   at MvvmCross.Forms.Droid.Views.MvxFormsApplicationActivity.InitializeForms (Android.OS.Bundle bundle) [0x00011] in C:\code\github\MvvmCross\MvvmCross-Forms\MvvmCross.Forms.Droid\Views\MvxFormsApplicationActivity.cs:107 
10-27 23:01:44.510 I/MonoDroid( 3625):   at MvvmCross.Forms.Droid.Views.MvxFormsApplicationActivity.OnCreate (Android.OS.Bundle bundle) [0x0002e] in C:\code\github\MvvmCross\MvvmCross-Forms\MvvmCross.Forms.Droid\Views\MvxFormsApplicationActivity.cs:100 
10-27 23:01:44.510 I/MonoDroid( 3625):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <484d528f6626418ea3cba8d2e5438e61>:0 
10-27 23:01:44.510 I/MonoDroid( 3625):   at (wrapper dynamic-method) System.Object:903113f0-8745-4ad0-a733-582df147f38e (intptr,intptr,intptr)`

### Configuration

**Version:** 5.x

**Platform:** 
- [ ] iOS
- [ X ] Android
- [ ] WPF
- [ ] UWP

**Comment by Giorgi** [comment]
I am getting the same error on a real device. Also there is a comment in MainViewModel.cs that says 

> In every platform: use the right Presenter (MvxFormsDroidMasterDetailPagePresenter, ...)

but I can't find MvxFormsDroidMasterDetailPagePresenter type in MvvmCross

**Comment by martijn00** [comment]
This should work in 5.3.2. Did you try that?

**Comment by martijn00** [comment]
Samples are moved to the Playground now for this. Reproduction seems to work, please test with 5.4.0 and report back if not fixed.

**Comment by Giorgi** [comment]
I cloned the repo yesterday and got this error so I guess it still happens in version 5.3.2

**Comment by ehuna** [comment]
I confirm that https://github.com/MvvmCross/MvvmCross/tree/develop/TestProjects/Playground/Playground.Forms.Droid is working, thanks!

I compiled Playground.Forms.Droid using https://github.com/MvvmCross/MvvmCross/blob/develop/MvvmCross_All.sln which compiles MvvmCross itself and all of its dependencies.

Next I will try to do it with 5.3.2 from https://www.nuget.org/packages/MvvmCross/

**Comment by ehuna** [comment]
I can confirm it does not work using the 5.3.2 nuget packages.

I removed the references to all MvvmCross projects and used the 5.3.2 nuget packages instead.  Here's what the updated Playground.Core packages.config looks like -

`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="MvvmCross" version="5.3.2" targetFramework="portable45-net45+win8" />
  <package id="MvvmCross.Binding" version="5.3.2" targetFramework="portable45-net45+win8" />
  <package id="MvvmCross.Core" version="5.3.2" targetFramework="portable45-net45+win8" />
  <package id="MvvmCross.Forms" version="5.3.2" targetFramework="portable45-net45+win8" />
  <package id="MvvmCross.Platform" version="5.3.2" targetFramework="portable45-net45+win8" />
  <package id="MvvmCross.Plugin.Json" version="5.3.2" targetFramework="portable45-net45+win8" />
  <package id="MvvmCross.Plugin.JsonLocalization" version="5.3.2" targetFramework="portable45-net45+win8" />
  <package id="MvvmCross.Plugin.ResourceLoader" version="5.3.2" targetFramework="portable45-net45+win8" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="portable45-net45+win8" />
  <package id="Xamarin.Forms" version="2.4.0.282" targetFramework="portable45-net45+win8+wpa81" />
</packages>`

At this point, when I try to compile Playground.Core, I get -

`1>------ Build started: Project: Playground.Core, Configuration: Debug Any CPU ------
1>C:\code\github\MvvmCross\TestProjects\Playground\Playground.Core\ViewModels\RootViewModel.cs(6,26,6,33): error CS0234: The type or namespace name 'Logging' does not exist in the namespace 'MvvmCross.Platform' (are you missing an assembly reference?)
1>C:\code\github\MvvmCross\TestProjects\Playground\Playground.Core\ViewModels\RootViewModel.cs(16,71,16,86): error CS0246: The type or namespace name 'IMvxLogProvider' could not be found (are you missing a using directive or an assembly reference?)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========`

You can see the changes here: https://github.com/MvvmCross/MvvmCross/pull/2323 (do not merge, sample pr just to show the above issue)

**Comment by martijn00** [comment]
That is because in 5.3.2 Logging doesn't exist. It is first added in 5.4. Are you using that code in 5.3.2?

**Comment by ehuna** [comment]
I'm just using the 'develop' branch of TestProjects\Playground\Playground.Core - see:

https://github.com/MvvmCross/MvvmCross/blob/develop/TestProjects/Playground/Playground.Core/ViewModels/RootViewModel.cs#L6

Is there a 5.3.2 branch of TestProjects\Playground\Playground.Core that I could use that does not reference Logging?

**Comment by martijn00** [comment]
You can pull down the tag for 5.3.2.

**Comment by ehuna** [comment]
Ah got it, my bad - I looked at branches, but completely ignored the tags.

Once I pulled for the 5.3.2 tag, it works as expected - thanks!

**Comment by ehuna** [comment]
Suggestion, in the 'Create Issue' template, you have:

### Configuration
**Version:** 5.x

In addition, you may want to add something like this:

### Source Code
**Branch:** develop
**Tag:** 5.3.2
